FROM python:3.7-stretch

WORKDIR /srv
ENTRYPOINT ["/srv/docker-entrypoint-dev.sh"]
CMD ["dev"]
EXPOSE 8000

RUN export DEBIAN_FRONTEND="noninteractive" && \
    curl -sL https://deb.nodesource.com/setup_10.x | bash - && \
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends libldap2-dev libsasl2-dev nodejs yarn netcat-openbsd

COPY requirements.txt /srv/
RUN pip install --upgrade pip && \
    pip install -r requirements.txt
