[tool.black]
line-length = 88
preview = true
target-version = ["py314"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist

    # The following are specific to Black, you probably don't want those.
    | blib2to3
    | tests/data
)/
'''

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.14"
django = ">=5.2,<5.3"
django-environ = "^0.14.0"
whitenoise = "^6.12.0"
django-reversion = "^5.0.4"
django-reversion-compare = "^0.16.2"
django-import-export = {extras = ["all"], version = "^4.0.0"}
djangorestframework = "^3.18.0"
django-filter = "^26.1"
django-health-check = "^4.5.1"
django-bootstrap3 = "^26.2"
google-api-python-client = "^2.200.0"
drf-writable-nested = "^0.7.0"
psycopg = {extras = ["binary"], version = "^3.3.5"}
google-auth = "^2.57.1"
gunicorn = "^26.2.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
django-debug-toolbar = "^8.0.0"
pytest = "^9.1.1"
black = "^26.5.1"
flake8 = "^7.3.0"
pyupgrade = "^3.21.2"
django-upgrade = "^1.32.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
