# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 21:11
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_squashed_0005_auto_20160612_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='post.Category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_items', to='post.Contact', verbose_name='recipient'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_items', to='post.Contact', verbose_name='sender'),
        ),
    ]
