# Generated by Django 2.1.7 on 2019-04-26 14:28

# Please note that a persons _membership_status will not get
# updated properly after this migration!
# You MUST run the clean_persons management command with --save!

from django.db import migrations
from django.db.models import F


def update_merit_members_without_from_date(apps, _schema_editor):
    member = apps.get_model("ldb", "Member")
    member.objects.filter(
        date_from__isnull=True,
        merit_date_from__isnull=False,
        honorary_date_from__isnull=True,
    ).update(date_from=F("merit_date_from"))


def update_honorary_members_without_from_date(apps, _schema_editor):
    member = apps.get_model("ldb", "Member")
    member.objects.filter(
        date_from__isnull=True, honorary_date_from__isnull=False
    ).update(date_from=F("honorary_date_from"))


class Migration(migrations.Migration):
    dependencies = [("ldb", "0013_auto_20170908_2246")]

    operations = [
        migrations.RunPython(
            update_merit_members_without_from_date, migrations.RunPython.noop
        ),
        migrations.RunPython(
            update_honorary_members_without_from_date, migrations.RunPython.noop
        ),
    ]
