# Generated by Django 2.1.7 on 2019-06-25 14:29

import dienst2.extras
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldb', '0013_auto_20170908_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='merit_history',
            field=models.TextField(blank=True, null=True, verbose_name='merit member history'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=dienst2.extras.CharNullField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_mobile',
            field=dienst2.extras.CharNullField(blank=True, max_length=16, null=True, verbose_name='phone mobile'),
        ),
        migrations.AlterField(
            model_name='person',
            name='postfix_titles',
            field=dienst2.extras.CharNullField(blank=True, max_length=20, null=True, verbose_name='postfix titles'),
        ),
        migrations.AlterField(
            model_name='person',
            name='preposition',
            field=dienst2.extras.CharNullField(blank=True, max_length=15, null=True, verbose_name='preposition'),
        ),
        migrations.AlterField(
            model_name='person',
            name='titles',
            field=dienst2.extras.CharNullField(blank=True, max_length=20, null=True, verbose_name='titles'),
        ),
        migrations.AlterField(
            model_name='student',
            name='emergency_name',
            field=dienst2.extras.CharNullField(blank=True, max_length=48, null=True, verbose_name='emergency name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='emergency_phone',
            field=dienst2.extras.CharNullField(blank=True, max_length=16, null=True, verbose_name='emergency phone'),
        ),
    ]
