# Generated by Django 2.2.8 on 2020-01-09 22:02

from django.db import migrations, models
import ldb.country_field


class Migration(migrations.Migration):

    dependencies = [
        ('ldb', '0014_auto_20190426_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='committee',
            options={'ordering': ['name'], 'verbose_name': 'commissie', 'verbose_name_plural': 'commissies'},
        ),
        migrations.AlterModelOptions(
            name='committeemembership',
            options={'ordering': ['board', 'committee__name'], 'verbose_name': 'commissielidmaatschap', 'verbose_name_plural': 'commissielidmaatschappen'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'medewerker', 'verbose_name_plural': 'medewerkers'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'entiteit', 'verbose_name_plural': 'entiteiten'},
        ),
        migrations.AlterModelOptions(
            name='modification',
            options={'verbose_name': 'wijziging', 'verbose_name_plural': 'wijzigingen'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'organisatie', 'verbose_name_plural': 'organisaties'},
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='contact_method',
            field=models.CharField(choices=[('m', 'Mail'), ('e', 'Email')], default='e', max_length=1, verbose_name='contact methode'),
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='study',
            field=models.CharField(blank=True, max_length=100, verbose_name='studie'),
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='study_first_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='eerste jaar studie'),
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='study_last_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='laatste jaar studie'),
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='study_research_group',
            field=models.CharField(blank=True, max_length=100, verbose_name='onderzoeksgroep'),
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='work_company',
            field=models.CharField(blank=True, max_length=100, verbose_name='bedrijf'),
        ),
        migrations.AlterField(
            model_name='alumnus',
            name='work_position',
            field=models.CharField(blank=True, max_length=100, verbose_name='functie'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='description',
            field=models.TextField(blank=True, verbose_name='beschrijving'),
        ),
        migrations.AlterField(
            model_name='committee',
            name='name',
            field=models.CharField(max_length=50, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='committeemembership',
            name='board',
            field=models.IntegerField(verbose_name='bestuur'),
        ),
        migrations.AlterField(
            model_name='committeemembership',
            name='position',
            field=models.CharField(blank=True, max_length=50, verbose_name='functie'),
        ),
        migrations.AlterField(
            model_name='committeemembership',
            name='ras_months',
            field=models.IntegerField(blank=True, null=True, verbose_name='RAS-maanden'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=50, verbose_name='afdeling'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='faculty',
            field=models.CharField(max_length=50, verbose_name='faculteit'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='function',
            field=models.CharField(max_length=50, verbose_name='functie'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_internal',
            field=models.CharField(max_length=5, verbose_name='telefoon intern'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='address_2',
            field=models.CharField(blank=True, max_length=75, verbose_name='adresregel 2'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='address_3',
            field=models.CharField(blank=True, max_length=75, verbose_name='adresregel 3'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='board_invites',
            field=models.BooleanField(default=False, verbose_name='uitnodigingen bestuur'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='christmas_card',
            field=models.BooleanField(default=True, verbose_name='Kerstkaartje'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='plaats'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='constitution_card',
            field=models.BooleanField(default=False, verbose_name='constitutiekaartje'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='country',
            field=ldb.country_field.CountryField(blank=True, choices=[('AF', 'Afghanistan'), ('AX', 'Ålandseilanden'), ('AL', 'Albanië'), ('DZ', 'Algerije'), ('AS', 'Amerikaans-Samoa'), ('AD', 'Andorra'), ('AO', 'Angola'), ('AI', 'Anguilla'), ('AQ', 'Antarctica'), ('AG', 'Antigua en Barbuda'), ('AR', 'Argentinië'), ('AM', 'Armenië'), ('AW', 'Aruba'), ('AU', 'Australië'), ('AT', 'Oostenrijk'), ('AZ', 'Azerbeidzjan'), ('BS', "Bahama's"), ('BH', 'Bahrein'), ('BD', 'Bangladesh'), ('BB', 'Barbados'), ('BY', 'Wit-Rusland / Belarus'), ('BE', 'België'), ('BZ', 'Belize'), ('BJ', 'Benin'), ('BM', 'Bermuda'), ('BT', 'Bhutan'), ('BO', 'Bolivia, Plurinationale Staat'), ('BQ', 'Bonaire, Sint Eustatius en Saba'), ('BA', 'Bosnië en Herzegovina'), ('BW', 'Botswana'), ('BV', 'Bouvet'), ('BR', 'Brazilië'), ('IO', 'Brits Territorium in de Indische Oceaan'), ('BN', 'Brunei'), ('BG', 'Bulgarije'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('KH', 'Cambodja'), ('CM', 'Kameroen'), ('CA', 'Canada'), ('CV', 'Kaap Verde'), ('KY', 'Kaaimaneilanden'), ('CF', 'Centraal-Afrikaanse Republiek'), ('TD', 'Tsjaad'), ('CL', 'Chili'), ('CN', 'China'), ('CX', 'Christmaseiland'), ('CC', 'Cocoseilanden'), ('CO', 'Colombia'), ('KM', 'Comoren'), ('CG', 'Congo-Brazzaville'), ('CD', 'Congo-Kinshasa'), ('CK', 'Cookeilanden'), ('CR', 'Costa Rica'), ('CI', 'Ivoorkust'), ('HR', 'Kroatië'), ('CU', 'Cuba'), ('CW', 'Curaçao'), ('CY', 'Cyprus'), ('CZ', 'Tsjechië'), ('DK', 'Denemarken'), ('DJ', 'Djibouti'), ('DM', 'Dominica'), ('DO', 'Dominicaanse Republiek'), ('EC', 'Ecuador'), ('EG', 'Egypte'), ('SV', 'El Salvador'), ('GQ', 'Equatoriaal-Guinea'), ('ER', 'Eritrea'), ('EE', 'Estland'), ('ET', 'Ethiopië'), ('FK', 'Falklandeilanden'), ('FO', 'Faeröer'), ('FJ', 'Fiji'), ('FI', 'Finland'), ('FR', 'Frankrijk'), ('GF', 'Frans-Guyana'), ('PF', 'Frans-Polynesië'), ('TF', 'Franse Zuidelijke en Antarctische Gebieden'), ('GA', 'Gabon'), ('GM', 'Gambia'), ('GE', 'Georgië'), ('DE', 'Duitsland'), ('GH', 'Ghana'), ('GI', 'Gibraltar'), ('GR', 'Griekenland'), ('GL', 'Groenland'), ('GD', 'Grenada'), ('GP', 'Guadeloupe'), ('GU', 'Guam'), ('GT', 'Guatemala'), ('GG', 'Guernsey'), ('GN', 'Guinee'), ('GW', 'Guinee-Bissau'), ('GY', 'Guyana'), ('HT', 'Haïti'), ('HM', 'Heardeiland en McDonaldeilanden'), ('VA', 'Vaticaanstad'), ('HN', 'Honduras'), ('HK', 'Hong Kong'), ('HU', 'Hongarije'), ('IS', 'IJsland'), ('IN', 'IndiaIndia'), ('ID', 'Indonesië'), ('IR', 'Iran'), ('IQ', 'Irak'), ('IE', 'Ierland'), ('IM', 'Man'), ('IL', 'Israël'), ('IT', 'Italië'), ('JM', 'Jamaica'), ('JP', 'Japan'), ('JE', 'Jersey'), ('JO', 'Jordanië'), ('KZ', 'Kazachstan'), ('KE', 'Kenia'), ('KI', 'KiribatiKiribati'), ('KP', 'Noord-Korea'), ('KR', 'Zuid-Korea'), ('KW', 'Koeweit'), ('KG', 'Kirgizië'), ('LA', 'Laos'), ('LV', 'Letland'), ('LB', 'Libanon'), ('LS', 'Lesotho'), ('LR', 'Liberia'), ('LY', 'Libië'), ('LI', 'Liechtenstein'), ('LT', 'Litouwen'), ('LU', 'Luxemburg'), ('MO', 'Macau'), ('MK', 'Macedonië'), ('MG', 'Madagaskar'), ('MW', 'Malawi'), ('MY', 'Maleisië'), ('MV', 'Maldiven'), ('ML', 'Mali'), ('MT', 'Malta'), ('MH', 'Marshalleilanden'), ('MQ', 'Martinique'), ('MR', 'Mauritanië'), ('MU', 'Mauritius'), ('YT', 'Mayotte'), ('MX', 'Mexico'), ('FM', 'Micronesië'), ('MD', 'Moldavië'), ('MC', 'Monaco'), ('MN', 'Mongolië'), ('ME', 'Montenegro'), ('MS', 'Montserrat'), ('MA', 'Marokko'), ('MZ', 'Mozambique'), ('MM', 'Myanmar'), ('NA', 'Namibië'), ('NR', 'Nauru'), ('NP', 'Nepal'), ('NL', 'Nederland'), ('NC', 'Nieuw-Caledonië'), ('NZ', 'Nieuw Zeeland'), ('NI', 'Nicaragua'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('NU', 'Niue'), ('NF', 'Norfolk'), ('MP', 'Noordelijke Marianen'), ('NO', 'Noorwegen'), ('OM', 'Oman'), ('PK', 'Pakistan'), ('PW', 'Palau'), ('PS', 'Palestijnse Gebieden'), ('PA', 'Panama'), ('PG', 'Papoea-Nieuw-Guinea'), ('PY', 'Paraguay'), ('PE', 'Peru'), ('PH', 'Filipijnen'), ('PN', 'Pitcairneilanden'), ('PL', 'Polen'), ('PT', 'Portugal'), ('PR', 'Puerto Rico'), ('QA', 'Qatar'), ('RE', 'Réunion'), ('RO', 'Roemenië'), ('RU', 'Rusland'), ('RW', 'Rwanda'), ('BL', 'Saint-Barthélemy'), ('SH', 'Sint-Helena, Ascension en Tristan da Cunha'), ('KN', 'Saint Kitts en Nevis'), ('LC', 'Saint Lucia'), ('MF', 'Saint-Martin'), ('PM', 'Saint-Pierre en Miquelon'), ('VC', 'Saint Vincent en de Grenadines'), ('WS', 'Samoa'), ('SM', 'San Marino'), ('ST', 'Sao Tomé en Principe'), ('SA', 'Saoedi-Arabië'), ('SN', 'Senegal'), ('RS', 'Servië'), ('SC', 'Seychellen'), ('SL', 'Sierra Leone'), ('SG', 'Singapore'), ('SX', 'Sint Maarten'), ('SK', 'Slowakije'), ('SI', 'Slovenië'), ('SB', 'Salomonseilanden'), ('SO', 'Somalië'), ('ZA', 'Zuid Afrika'), ('GS', 'Zuid-Georgië en de Zuidelijke Sandwicheilanden'), ('ES', 'Spanje'), ('LK', 'Sri Lanka'), ('SD', 'Soedan'), ('SR', 'Suriname'), ('SJ', 'Spitsbergen en Jan Mayen'), ('SZ', 'Swaziland'), ('SE', 'Zweden'), ('CH', 'Zwitserland'), ('SY', 'Syrië'), ('TW', 'Taiwan'), ('TJ', 'Tadzjikistan'), ('TZ', 'Tanzania'), ('TH', 'Thailand'), ('TL', 'Oost-Timor'), ('TG', 'Togo'), ('TK', 'Tokelau-eilanden'), ('TO', 'Tonga'), ('TT', 'Trinidad en Tobago'), ('TN', 'Tunesië'), ('TR', 'Turkije'), ('TM', 'Turkmenistan'), ('TC', 'Turks- en Caicoseilanden'), ('TV', 'Tuvalu'), ('UG', 'Oeganda'), ('UA', 'Oekraïne'), ('AE', 'Verenigde Arabische Emiraten'), ('GB', 'Verenigd Koninkrijk'), ('US', 'Verenigde Staten'), ('UM', 'Kleine afgelegen eilanden van de Verenigde Staten'), ('UY', 'Uruguay'), ('UZ', 'Oezbekistan'), ('VU', 'Vanuatu'), ('VE', 'Venezuela'), ('VN', 'Vietnam'), ('VG', 'Maagdeneilanden, Brits'), ('VI', 'Maagdeneilanden, Amerikaans'), ('WF', 'Wallis en Futuna'), ('EH', 'Westelijke Sahara'), ('YE', 'Jemen'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe')], max_length=2, verbose_name='land'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='house_number',
            field=models.CharField(blank=True, max_length=7, verbose_name='huisnummer'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='phone_fixed',
            field=models.CharField(blank=True, max_length=16, verbose_name='telefoon vast'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='street_name',
            field=models.CharField(blank=True, max_length=75, verbose_name='straatnaam'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='yearbook',
            field=models.BooleanField(default=False, verbose_name='jaarboek'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='datum'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='ip',
            field=models.CharField(max_length=40, verbose_name='ip adres'),
        ),
        migrations.AlterField(
            model_name='modification',
            name='modification',
            field=models.TextField(blank=True, verbose_name='wijziging'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name_prefix',
            field=models.CharField(blank=True, max_length=100, verbose_name='naam voorvoegsel'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name_short',
            field=models.CharField(blank=True, max_length=100, verbose_name='naam kort'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='salutation',
            field=models.CharField(max_length=100, verbose_name='aanhef'),
        ),
    ]
