# Generated by Django 2.2.12 on 2020-05-28 11:44

from django.db import migrations, models

import ldb.validators


class Migration(migrations.Migration):
    dependencies = [("ldb", "0017_email_forward_view")]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="facebook_id",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Facebook ID",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="ldap_username",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                validators=[ldb.validators.validate_ldap_username],
                verbose_name="LDAP username",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="linkedin_id",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="LinkedIn ID",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="netid",
            field=models.CharField(
                blank=True, max_length=64, null=True, unique=True, verbose_name="NetID"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="student_number",
            field=models.CharField(
                blank=True,
                max_length=7,
                null=True,
                unique=True,
                verbose_name="student number",
            ),
        ),
    ]
