# Generated by Django 2.2.28 on 2023-07-05 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ldb", "0021_person_google_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entity",
            name="board_invites",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="christmas_card",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="constitution_card",
        ),
        migrations.RemoveField(
            model_name="entity",
            name="yearbook",
        ),
        migrations.RemoveField(
            model_name="student",
            name="yearbook_permission",
        ),
    ]
