# Generated by Django 4.2.6 on 2023-10-12 09:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ldb", "0023_alter_entity_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="email_forward",
        ),
    ]
