# Generated by Django 4.2.22 on 2025-09-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ldb", "0024_remove_person_email_forward"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="house_number",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="house number"
            ),
        ),
    ]
